src/website/views.py
from flask import Blueprint, render_template, request, flash, url_for, redirect
from flask_login import login_required, current_user
from sqlalchemy.exc import SQLAlchemyError
from .models import Transaction, Category, Period, History
from . import db

views = Blueprint('views', __name__)


def query_object_add(query_element):
    db.session.add(query_element)
    db.session.commit()


def query_object_delete(query_element):
    db.session.delete(query_element)
    db.session.commit()


def get_overall_svg():
    return [current_user.generate_all_outcomes_by_category(), current_user.generate_all_outcomes_with_limits(),
            current_user.generate_incomes_outcomes_plot()]


def get_categories_svg():
    svgs = []
    for category in current_user.categories:
        svgs.append(current_user.plot_data(category.name))
    return svgs


@views.route('/categories', methods=['GET', 'POST'])
@views.route('/', methods=['GET', 'POST'])
@login_required
def home():
    if request.method != 'POST':
        if request.path == '/categories':
            return render_template("home.html", user=current_user, svgs=get_categories_svg())
        else:
            return render_template("home.html", user=current_user, svgs=get_overall_svg())

    if current_user.active_period:
        try:
            transaction_value = int(request.form.get('transaction_value'))
            transaction_desc = request.form.get('transaction_desc')
            transaction_category = request.form.get('transaction_category')
            transaction_outcome = request.form.get('transaction_outcome')

            if transaction_category == '0':
                flash('Category was not set!', category='error')
                return render_template("home.html", user=current_user, svgs=get_overall_svg())

            if transaction_outcome:
                transaction_value = -abs(transaction_value)
                transaction_outcome = False
            else:
                transaction_value = abs(transaction_value)
                transaction_outcome = True

            if len(transaction_desc) < 1:
                flash('Please insert transaction description', category='error')
            else:
                new_transaction = Transaction(value=transaction_value, description=transaction_desc,
                                              category=transaction_category, outcome=transaction_outcome,
                                              user_id=current_user.id)
                query_object_add(new_transaction)
                flash('Transaction added!', category='success')

        except ValueError:
            flash('Transaction value should be a number!', category='error')
    else:
        flash('No period started!', category='error')
    return render_template("home.html", user=current_user, svgs=get_overall_svg())


@views.route('/settings', methods=['GET', 'POST'])
@login_required
def settings():
    if request.method != 'POST':
        return render_template("settings.html", user=current_user)

    try:
        category_name = request.form.get('category_name')
        category_limit = request.form.get('category_limit')
        period_name = request.form.get('period_name')

        if category_name:
            if len(category_name) < 3:
                flash('Category name should be at least 3 characters long', category='error')
            elif category_limit == '':
                flash('Category limit shall not be empty!', category='error')
            else:
                try:
                    if db.session.query(Category).filter(Category.name == category_name).first():
                        flash('Such category name already exists!', category='error')
                    else:
                        category_limit = int(category_limit)
                        new_category = Category(name=category_name, limit=category_limit, user_id=current_user.id)
                        query_object_add(new_category)
                        flash('Category added!', category='success')
                except SQLAlchemyError:
                    flash('Category limit value should be a number!', category='error')

        if period_name:
            period = db.session.query(Period).filter(Period.name == period_name).first()
            if period:
                flash('There is already an active period!', category='error')
                return render_template("settings.html", user=current_user)
            if len(current_user.categories) > 0:
                if len(period_name) < 3:
                    flash('Period name should be at least 3 characters', category='error')
                else:
                    if db.session.query(History).filter(History.name == period_name).first():
                        flash('Such period name was already used in the past!', category='error')
                    else:
                        new_period = Period(name=period_name, user_id=current_user.id)
                        query_object_add(new_period)
                        flash('Period started!', category='success')
            else:
                flash('You need to have at least one transaction category created before starting new period!',
                      category='error')

        if all(field is None for field in [category_name, category_limit, period_name]):
            if current_user.active_period:
                try:
                    new_history = History(name=current_user.active_period[0].name,
                                          outcomes=current_user.get_total_transaction_value(False),
                                          incomes=current_user.get_total_transaction_value(True),
                                          user_id=current_user.id)
                    query_object_add(new_history)
                    period = Period.query.get(current_user.active_period[0].id)
                    if period and period.user_id == current_user.id:
                        db.session.query(Transaction).delete()
                        query_object_delete(period)
                        flash('Period finished!', category='success')
                except SQLAlchemyError:
                    db.session.rollback()
            else:
                flash('There is no active period!', category='error')
    except ValueError:
        flash('Category limit value should be a number!', category='error')

    return render_template("settings.html", user=current_user)


@views.route('/history')
@login_required
def history():
    history_chart = current_user.get_month_statistics()
    return render_template("history.html", user=current_user, svg=history_chart)


@views.route('/edit_transaction/<int:transaction_id>', methods=['POST'])
@login_required
def edit_transaction(transaction_id):
    transaction = Transaction.query.get(transaction_id)
    if request.method == 'POST':
        if transaction is None:
            flash('There is no such transaction ID!', category='error')
            return render_template("home.html", user=current_user)
        transaction_value = request.form.get('transaction_value')
        transaction_desc = request.form.get('transaction_desc')
        transaction_category = request.form.get('transaction_category')
        transaction_outcome = request.form.get('transaction_outcome')

        if all(field is None for field in [transaction_value, transaction_desc, transaction_category,
                                           transaction_outcome]):
            return render_template("edit_transaction.html", user=current_user, transaction_value=transaction.value,
                                   transaction_desc=transaction.description,
                                   transaction_category=transaction.category,
                                   transaction_outcome=transaction.outcome)

        if transaction_category == '0':
            flash('Category was not set!', category='error')
        elif len(transaction_desc) < 1:
            flash('Please insert transaction description', category='error')
        else:
            try:
                if transaction_outcome:
                    transaction.value = -abs(int(transaction_value))
                    transaction.outcome = False
                else:
                    transaction.value = abs(int(transaction_value))
                    transaction.outcome = True
                transaction.description = transaction_desc
                transaction.category = transaction_category
                db.session.commit()
                flash('Transaction was updated!')
                return redirect(url_for('views.home'))
            except ValueError:
                flash('Transaction value should be a number!', category='error')

    return render_template("edit_transaction.html", user=current_user, transaction_value=transaction.value,
                           transaction_desc=transaction.description,
                           transaction_category=transaction.category,
                           transaction_outcome=transaction.outcome)


@views.route('/delete_transaction/<int:transaction_id>', methods=['POST'])
@login_required
def delete_transaction(transaction_id):
    if request.method == 'POST':
        try:
            transaction = Transaction.query.get(transaction_id)
            if transaction and transaction.user_id == current_user.id:
                query_object_delete(transaction)
                flash('Transaction was deleted successfully!', category='success')
            else:
                flash('There is no such transaction ID!', category='error')
        except SQLAlchemyError:
            db.session.rollback()
    return redirect(url_for('views.home'))


@views.route('/edit_category/<int:category_id>', methods=['POST'])
@login_required
def edit_category(category_id):
    category = Category.query.get(category_id)
    category_name = request.form.get('category_name')
    category_limit = request.form.get('category_limit')

src/website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
      <meta charset="utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
      <title>{% block title %}Jumpy Saola{% endblock %}</title>
  </head>
  <body>
      <div class="topnav">
          <a href="/">Home</a>
          {% if user.is_authenticated %}
            <a href="/history">History</a>
            <a href="/settings">Settings</a>
          {% endif %}
          <div class="topnav-right">
              {% if user.is_authenticated %}
                <a href="/logout">Logout</a>
              {% else %}
                <a href="/login">Login</a>
                <a href="/signup">Sign Up</a>
              {% endif %}
          </div>
      </div>
{% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        {% for category, message in messages %}
            {% if category ==  'error' %}
    <div class="failure">
        <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
        <strong>Warning!</strong> {{ message }}
    </div>
    {% else %}
    <div class="success">
        <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
        <strong>Success!</strong> {{ message }}
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <div class="container">{% block content %} {% endblock %}</div>
  </body>
</html>

src/website/templates/edit_category.html
{% extends "base.html" %} {% block title %}Settings{% endblock %} {% block content
%}
<h1 align="center">Edit category</h1>
<form method="POST">
  <div class="col">
    <input class="btn" type="text" id="category_name" name="category_name" placeholder="Name" value="{{ category_name }}">
    <br />
    <input class="btn" type="number" id="category_limit" name="category_limit" placeholder="Limit" value="{{ category_limit }}">
    <br />
    <input id="submit" class="btn" type="submit" value="Submit">
  </div>
</form>
{% endblock %}

src/website/templates/edit_transaction.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block content %}
<form method="POST">
      <h1>{{ user.active_period[0].name }}</h1>
      <div class="col">
      <input class="btn" type="number" name="transaction_value" placeholder="Transaction value" value="{{ transaction_value }}">
      <input class="btn" type="text" name="transaction_desc" placeholder="Description" value="{{ transaction_desc }}">
          <select name="transaction_category" id="transaction_category">
              <option value="0">Categories</option>
              {% for category in user.categories %}
              <option>{{ category.name }}</option>
              {% endfor %}
          </select>
          <div class="checkbox">
              <div class="tooltip">
                  <input id="transaction_outcome" type="checkbox" class="larger" name="transaction_outcome" checked>
                  <label for="transaction_outcome">Outcome</label>
                  <span class="tooltiptext">Uncheck this field if transaction is an income</span>
              </div>
              <input id="submit" class="btn" type="submit" value="Submit">
          </div>
      </div>
  </form>
{% endblock %}

src/website/templates/history.html
{% extends "base.html" %} {% block title %}History{% endblock %} {% block content %}
{% if user.history|length > 0 %}
<h1 align="center">History</h1>
<table id="categories_table">
  <tr>
    <th>Period</th>
    <th>Outcomes</th>
    <th>Incomes</th>
    <th>Options</th>
  </tr>
      {% for period in user.history %}
        <tr>
            <td>{{ period.name }}</td>
            <td>{{ period.outcomes }}</td>
            <td>{{ period.incomes }}</td>
            <td>
                <form action="{{ url_for('views.delete_period', period_id=period.id) }}" method="post">
                    <button id="delete" type="submit" name="delete" class="aslink redlink">Delete</button>
                </form>
            </td>
        </tr>
      {% endfor %}
</table>
<div id="chart">
    <embed class="chart" type="image/svg+xml" src= {{ svg|safe }} />
</div>
{% else %}
  <h1 align="center">There are no periods in history to show!</h1>
{% endif %}
{% endblock %}

src/website/templates/home.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block content %}
{% if user.active_period|length > 0 %}
<form method="POST">
      <h1>{{ user.active_period[0].name }}</h1>
      <div class="col">
      <input class="btn" type="number" name="transaction_value" placeholder="Transaction value" required>
      <input class="btn" type="text" minlength="3" name="transaction_desc" placeholder="Description" required>
          <select name="transaction_category" id="transaction_category">
              <option value="0">Categories</option>
              {% for category in user.categories %}
              <option>{{ category.name }}</option>
              {% endfor %}
          </select>
          <div class="checkbox">
              <div class="tooltip">
                  <input id="transaction_outcome" type="checkbox" class="larger" name="transaction_outcome" value="transaction_outcome" checked>
                  <label for="transaction_outcome">Outcome</label>
                  <span class="tooltiptext">Uncheck this field if transaction is an income</span>
              </div>
              <input id="add_transaction" class="btn" type="submit" value="Add transaction">
          </div>
      </div>
  </form>
  {% if user.transactions|length > 0 %}
  <table id="categories_table">
      <tr>
          <th>Value</th>
          <th>Description</th>
          <th>Category</th>
          <th>Options</th>
      </tr>
      {% for transaction in user.transactions %}
      <tr>
          <td>{{ transaction.description }}</td>
          <td>{{ transaction.value }}</td>
          <td>{{ transaction.category }}</td>
          <td>
              <form action="{{ url_for('views.edit_transaction', transaction_id=transaction.id) }}" method="post">
                <button type="submit" name="edit" class="aslink">Edit</button>
              </form>
              <form action="{{ url_for('views.delete_transaction', transaction_id=transaction.id) }}" method="post">
                <button type="submit" name="delete" class="aslink redlink">Delete</button>
              </form>
          </td>
      </tr>
      {% endfor %}
      <tr>
          <th>Summary</th>
          <th>{{ user.get_total_transaction_value(False) + user.get_total_transaction_value(True)  }}</th>
          <th></th>
          <th></th>
      </tr>
  </table>
    <div class="middlenav">
        <a href="/">Overall</a>
        <a href="/categories">Categories</a>
    </div>
    {% for svg in svgs %}
        <div id="chart">
            <embed class="chart" type="image/svg+xml" src= {{ svg|safe }} />
        </div>
    {% endfor %}
{% endif %}
{% else %}
  <h1 align="center">No active period! Go to settings and start one!</h1>
{% endif %}
{% endblock %}

src/website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %} {% block content %}
<form method="POST">
  <div class="col">
  <h2 align="center">Login</h2>
    <input type="text" class="btn" minlength="3" id="username" name="username" placeholder="Enter username"/>
    <input type="password" minlength="4" maxlength="4" class="btn" id="pin_code" name="pin_code" placeholder="Enter pin code" />
    <input id="login" class="btn" type="submit" value="Login">
    </div>
</form>
{% endblock %}

src/website/templates/settings.html
{% extends "base.html" %} {% block title %}Settings{% endblock %} {% block content
%}
<h1 align="center">Settings</h1>
{% if user.categories|length > 0 %}
<table id="categories_table">
<tr>
  <th>Category</th>
  <th>Limit</th>
  <th>Options</th>
</tr>
    {% for category in user.categories %}
      <tr>
        <td>{{ category.name }}</td>
        <td>{{ category.limit }}</td>
        <td>
          <form action="{{ url_for('views.edit_category', category_id=category.id) }}" method="post">
            <button type="submit" name="edit" class="aslink">Edit</button>
          </form>
          <form action="{{ url_for('views.delete_category', category_id=category.id) }}" method="post">
            <button type="submit" name="delete" class="aslink redlink">Delete</button>
          </form>
          </td>
      </tr>
    {% endfor %}
  <tr>
    <th>Summary</th>
    <th>{{ user.get_total_limit() }}</th>
    <th></th>
  </tr>
</table>
{% endif %}
<h2 align="center">Categories</h2>
<form method="POST">
  <div class="col">
    <input class="btn" type="text" id="category_name" name="category_name" placeholder="Name">
    <br />
    <input class="btn" type="number" id="category_limit" name="category_limit" placeholder="Limit">
    <br />
    <input id="add_category" class="btn" type="submit" value="Add category">
  </div>
</form>
<br />
<br />
<form method="POST">
  <div class="col">
    {% if user.active_period|length > 0 %}
      <h2 align="center">Actual period: {{ user.active_period[0].name }}</h2>
      <input id="stop_period" class="btn" type="submit" style="background-color: #ff0000" value="Stop period">
    {% else %}
      <h2 align="center">No active period</h2>
      <input class="btn" type="text" id="period_name" name="period_name" placeholder="Period name" required>
      <input id="start_period" class="btn" type="submit" value="Start period">
      {% endif %}
  </div>
</form>
{% endblock %}

src/website/templates/sign_up.html
{% extends "base.html" %} {% block title %}Sign Up{% endblock %} {% block content %}
<form method="POST">
  <div class="col">
  <h2 align="center">Sign Up</h2>
    <input type="text" class="btn" minlength="3" id="username"  name="username" placeholder="Enter username"/>
    <input type="password" minlength="4" maxlength="4" class="btn" id="pin_code_1" name="pin_code_1" placeholder="Enter pin code"/>
    <input type="password" minlength="4" maxlength="4" class="btn" id="pin_code_2" name="pin_code_2" placeholder="Confirm pin code"/>
  <input id="submit" class="btn" type="submit" value="Submit">
  </div>
</form>
{% endblock %}